title: Laura Pilkington
logo: /assets/img/logo.png
description: Hello, my name is Laura and I work remotely as a freelance data analyst.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
